export interface Vehicle {
  id: string
  userId: string
  make: string
  model: string
  variant?: string
  year: number
  price: number
  mileage: number
  fuel: string
  engineCapacity: string
  transmission: string
  bodyType: string
  exteriorColor: string
  interiorColor: string
  description?: string
  images: string[]
  image?: string
  location: string
  sellerName: string
  sellerEmail: string
  sellerPhone: string
  sellerSuburb?: string
  sellerCity?: string
  sellerProvince?: string
  sellerProfilePic?: string
  status: string
  createdAt: string
  updatedAt: string
}
